# Generated by Django 4.2.2 on 2024-01-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityModel',
            fields=[
                ('community_name', models.CharField(max_length=30)),
                ('community_Key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('introduce', models.TextField(default='紹介文を入力', max_length=300)),
                ('is_RegistByEmail', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('Customdata', models.TextField(default='プロフィールを入力', max_length=1000)),
                ('custom_user_Name', models.CharField(max_length=50)),
                ('custom_user_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/custom/')),
                ('Community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customUser.communitymodel')),
                ('PersonalData', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.personaldata')),
            ],
        ),
    ]
