# Generated by Django 4.2.7 on 2023-12-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='customdata',
            field=models.TextField(default='プロフィールを入力', max_length=1000),
        ),
    ]
