# Generated by Django 4.2.7 on 2023-12-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0002_customusermodel_customdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='customdata',
            new_name='Customdata',
        ),
    ]
