# Generated by Django 4.2.7 on 2023-12-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0004_alter_communitymodel_community_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymodel',
            name='introduce',
            field=models.TextField(max_length=300),
        ),
    ]
