# Generated by Django 4.2.7 on 2023-12-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0005_alter_communitymodel_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymodel',
            name='introduce',
            field=models.TextField(default='紹介文を入力', max_length=300),
        ),
    ]
