# Generated by Django 4.2.7 on 2024-01-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='quiz/static/quiz/images/no_image_square.jpg', upload_to='images/quiz/'),
        ),
    ]
