# Generated by Django 4.2.7 on 2023-12-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='id',
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='user_key',
            field=models.CharField(max_length=33, primary_key=True, serialize=False),
        ),
    ]
