# Generated by Django 4.2.2 on 2024-01-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommodel',
            name='chat_data',
            field=models.TextField(),
        ),
    ]
