# Generated by Django 4.2.2 on 2024-01-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroommodel_chat_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommodel',
            name='chat_data',
            field=models.TextField(default=''),
        ),
    ]
